version: '3.1'

services:

#  mysql:
#    image: mysql
#    ports:
#      - 3307:3307
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: senha123
#      MYSQL_DATABASE: RASPLUS
#      MYSQL_USER: rasmoo
#      MYSQL_PASSWORD: senha123
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
