version: '3.1'

services:

  mysql:
    image: mysql
    ports:
      - 3307:3307
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: RASPLUS
      MYSQL_USER: rasmoo
      MYSQL_PASSWORD: senha123
